name: Language Linting
on: [push, pull_request]

jobs:
  alex-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: alex
        uses: theashraf/alex-action@master
